MANTA-4852 rename manta-picker service to something more accurate
joyent/manta-picker pull request #12
Opened 2020-01-25 02:59 UTC by rejohnst

2020-01-25 03:01 UTC, rejohnst commented
Note, there is a companion PR for the sdc-manta repo (https://github.com/joyent/sdc-manta/pull/55) which I've asked Trent to look at, though you're welcome to look at it, as well.

2020-01-27 18:56 UTC, trentm requested changes
There are still some "picker" hits:

```
README.md
5:A draft RFD describing the motivation, requirements and approach for manta-storinfo is [here](https://github.com/joyent/rfd/tree/master/rfd/0170).  The Picker API is documented [here](https://github.com/joyent/manta-storinfo/blob/master/docs/index.md)

package.json
9:    "url": "git+ssh://git@github.com:joyent/manta-picker.git"

smf/manifests/storinfo.xml.in
31:            <common_name><loctext xml:lang="C">Manta Picker Service</loctext></common_name>

smf/manifests/picker.xml
13:<service_bundle type="manifest" name="picker">
14:    <service name="manta/application/picker" type="service" version="1">
31:            <common_name><loctext xml:lang="C">Manta Picker Service</loctext></common_name>
```

2020-01-27 22:25 UTC, rejohnst commented
Thanks for spotting those - fixed.

2020-01-27 23:02 UTC, trentm approved these changes

2020-01-29 18:54 UTC, merged